serverAddr = "192.168.5.2"
serverPort = 9903

transport.tls.enable = true

log.to = "console"
# trace, debug, info, warn, error
log.level = "info"

[auth]
method = "token"
token = "19a4a6e3-0c14-4e49-9d3f-32f1d621b13d"

[[proxies]]
name = "local-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 9904
transport.useEncryption = false
transport.useCompression = false
